version: '3.8'

services:
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabbit
    image: rabbitmq:latest
    networks:
      - my-network-name
    # healthcheck:
    #     test: ["CMD", "curl", "-f", "http://localhost:15672"]
    #     interval: 30s
    #     timeout: 10s
    #     retries: 5

  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - 27019:27017
    networks:
      - my-network-name

  messageprocessor:
    image: ${DOCKER_REGISTRY-}messageprocessor
    build:
      context: .
      dockerfile: src\MessageProcessor\Dockerfile
    restart: on-failure
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - my-network-name

  messagepublisherapi:
    image: ${DOCKER_REGISTRY-}messagepublisherapi
    build:
      context: .
      dockerfile: src\MessagePublisherApi\Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - my-network-name

volumes:
  mongodb:
  mongodb_config:

networks:
  my-network-name: